
//------------------------------------------------------------------
// ENVIO OPERACIONES
//------------------------------------------------------------------
//------------INICIO VENTA sola
if(posicionesabiertasrobotv==0){


  if(filtermatrend==TRUE&&matend==2){
    if(filterHisto==TRUE&&tendhisto==2){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
  }
  if(filtermatrend==FALSE){
    if(filterHisto==TRUE&&tendhisto==2){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
  }


  }

  //------------Fin venta sola
//------------INICIO COMPRA sola

if(posicionesabiertasrobotc==0){



  if(filtermatrend==TRUE&&matend==1){
    if(filterHisto==TRUE&&tendhisto==1){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
  }
  if(filtermatrend==FALSE){
    if(filterHisto==TRUE&&tendhisto==1){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
  }


   }
//-------------FIN COMPRA SOLA
//----------------INICIO VENTA GRUPAL
if(posicionesabiertasrobotv>0&&filter1v==1&&posicionesabiertasrobotv<maxposition){



  if(filtermatrend==TRUE&&matend==2){
    if(filterHisto==TRUE&&tendhisto==2){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
  }
  if(filtermatrend==FALSE){
    if(filterHisto==TRUE&&tendhisto==2){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==2){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==2){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==2){
          if(filterbollingerbands==TRUE&&tendbollinger==2){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==2){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_SELL,lotesposicionv,Bid,Slippage,0,0,"MUFASA",MagicNumber,0,Red);
            }
          }
        }
      }
    }
  }


}

//----------------FIN VENTA GRUPAL
//----------------INICIO COMPRA GRUPAL
if(posicionesabiertasrobotc>0&&filter1c==1&&posicionesabiertasrobotc<maxposition){




  if(filtermatrend==TRUE&&matend==1){
    if(filterHisto==TRUE&&tendhisto==1){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
  }
  if(filtermatrend==FALSE){
    if(filterHisto==TRUE&&tendhisto==1){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
    if(filterHisto==FALSE){
      if(filterFish==TRUE&&tendfisher==1){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
      if(filterFish==FALSE){
        if(Resistanceopenfilter==TRUE&&Filterresistance==1){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
        if(Resistanceopenfilter==FALSE){
          if(filtermirror==TRUE&&tendmirror==1){
          if(filterbollingerbands==TRUE&&tendbollinger==1){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          if(filterbollingerbands==FALSE){
            OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
          }
          }
          if(filtermirror==FALSE){
            if(filterbollingerbands==TRUE&&tendbollinger==1){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
            if(filterbollingerbands==FALSE){
              OrderSend(Symbol(),OP_BUY,lotesposicionc,Ask,Slippage,0,0,"MUFASA",MagicNumber,0,Blue);
            }
          }
        }
      }
    }
  }



  }



//FIN COMPRA GRUPAL
